name: impact_vuscan
channels:
  - bioconda
  - r
  - conda-forge
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=2_gnu
  - _r-mutex=1.0.1=anacondar_1
  - argcomplete=3.6.2=pyhd8ed1ab_0
  - binutils_impl_linux-64=2.44=h4bf12b8_1
  - bioconductor-biobase=2.66.0=r44h3df3fcb_0
  - bioconductor-biocgenerics=0.52.0=r44hdfd78af_3
  - bioconductor-biocio=1.16.0=r44hdfd78af_0
  - bioconductor-biocparallel=1.40.0=r44he5774e6_1
  - bioconductor-biostrings=2.74.0=r44h3df3fcb_1
  - bioconductor-bsgenome=1.74.0=r44hdfd78af_0
  - bioconductor-bsgenome.hsapiens.ucsc.hg38=1.4.5=r44hdfd78af_3
  - bioconductor-complexheatmap=2.22.0=r44hdfd78af_0
  - bioconductor-data-packages=20250625=hdfd78af_0
  - bioconductor-delayedarray=0.32.0=r44h3df3fcb_1
  - bioconductor-dnacopy=1.80.0=r44h4d5c4aa_1
  - bioconductor-genomeinfodb=1.42.0=r44hdfd78af_2
  - bioconductor-genomeinfodbdata=1.2.13=r44hdfd78af_0
  - bioconductor-genomicalignments=1.42.0=r44h3df3fcb_1
  - bioconductor-genomicranges=1.58.0=r44h3df3fcb_2
  - bioconductor-iranges=2.40.0=r44h3df3fcb_2
  - bioconductor-maftools=2.22.0=r44h15a9599_0
  - bioconductor-matrixgenerics=1.18.0=r44hdfd78af_0
  - bioconductor-rhtslib=3.2.0=r44h15a9599_2
  - bioconductor-rsamtools=2.22.0=r44h77050f0_1
  - bioconductor-rtracklayer=1.66.0=r44h15a9599_1
  - bioconductor-s4arrays=1.6.0=r44h3df3fcb_1
  - bioconductor-s4vectors=0.44.0=r44h3df3fcb_2
  - bioconductor-sparsearray=1.6.0=r44h3df3fcb_1
  - bioconductor-summarizedexperiment=1.36.0=r44hdfd78af_0
  - bioconductor-ucsc.utils=1.2.0=r44h9ee0642_1
  - bioconductor-xvector=0.46.0=r44h15a9599_2
  - bioconductor-zlibbioc=1.52.0=r44h3df3fcb_2
  - bottleneck=1.6.0=np2py310h99de88f_3
  - bwidget=1.10.1=ha770c72_1
  - bzip2=1.0.8=hda65f42_8
  - c-ares=1.34.5=hb9d3cd8_0
  - ca-certificates=2025.11.12=hbd8a1cb_0
  - cairo=1.18.4=h3394656_0
  - curl=8.14.1=h332b0f4_0
  - font-ttf-dejavu-sans-mono=2.37=hab24e00_0
  - font-ttf-inconsolata=3.000=h77eed37_0
  - font-ttf-source-code-pro=2.038=h77eed37_0
  - font-ttf-ubuntu=0.83=h77eed37_3
  - fontconfig=2.15.0=h7e30c49_1
  - fonts-conda-ecosystem=1=0
  - fonts-conda-forge=1=0
  - freetype=2.14.0=ha770c72_1
  - fribidi=1.0.16=hb03c661_0
  - gcc_impl_linux-64=15.1.0=h4393ad2_5
  - gfortran_impl_linux-64=15.1.0=h3b9cdf2_5
  - graphite2=1.3.14=hecca717_2
  - gsl=2.7=he838d99_0
  - gxx_impl_linux-64=15.1.0=h6a1bac1_5
  - harfbuzz=11.4.5=h15599e2_0
  - htslib=1.22.1=h566b1c6_0
  - icu=75.1=he02047a_0
  - jq=1.5=0
  - kernel-headers_linux-64=4.18.0=he073ed8_8
  - keyutils=1.6.3=hb9d3cd8_0
  - krb5=1.21.3=h659f571_0
  - ld_impl_linux-64=2.44=h1423503_1
  - lerc=4.0.0=h0aef613_1
  - libblas=3.9.0=35_h4a7cf45_openblas
  - libcblas=3.9.0=35_h0358290_openblas
  - libcurl=8.14.1=h332b0f4_0
  - libdeflate=1.24=h86f0d12_0
  - libedit=3.1.20250104=pl5321h7949ede_0
  - libev=4.33=hd590300_2
  - libexpat=2.7.1=hecca717_0
  - libffi=3.4.6=h2dba641_1
  - libfreetype=2.14.0=ha770c72_1
  - libfreetype6=2.14.0=h73754d4_1
  - libgcc=15.1.0=h767d61c_4
  - libgcc-devel_linux-64=15.1.0=h4c094af_105
  - libgcc-ng=15.1.0=h69a702a_4
  - libgfortran=15.1.0=h69a702a_5
  - libgfortran-ng=15.1.0=h69a702a_5
  - libgfortran5=15.1.0=hcea5267_5
  - libgit2=1.9.1=h014eb84_0
  - libglib=2.84.3=hf39c6af_0
  - libgomp=15.1.0=h767d61c_4
  - libiconv=1.18=h3b78370_2
  - libjpeg-turbo=3.1.0=hb9d3cd8_0
  - liblapack=3.9.0=35_h47877c9_openblas
  - liblzma=5.8.1=hb9d3cd8_2
  - libnghttp2=1.67.0=had1ee68_0
  - libnsl=2.0.1=hb9d3cd8_1
  - libopenblas=0.3.30=pthreads_h94d23a6_2
  - libpng=1.6.50=h421ea60_1
  - libsanitizer=15.1.0=h97b714f_5
  - libsqlite=3.50.4=h0c1763c_0
  - libssh2=1.11.1=hcf80075_0
  - libstdcxx=15.1.0=h8f9b012_4
  - libstdcxx-devel_linux-64=15.1.0=h4c094af_105
  - libstdcxx-ng=15.1.0=h4852527_4
  - libtiff=4.7.0=h8261f1e_6
  - libuuid=2.41.1=he9a06e4_0
  - libuv=1.51.0=hb03c661_1
  - libwebp-base=1.6.0=hd42ef1d_0
  - libxcb=1.17.0=h8a09558_0
  - libxcrypt=4.4.36=hd590300_1
  - libxml2=2.13.8=h04c0eec_1
  - libzlib=1.3.1=hb9d3cd8_2
  - make=4.4.1=hb9d3cd8_2
  - ncurses=6.5=h2d0b736_3
  - nlopt=2.10.0=py310h699ddf3_1
  - nomkl=1.0=h5ca1d4c_0
  - numexpr=2.14.1=py310h34a7263_101
  - numpy=2.2.6=py310hefbff90_0
  - openssl=3.6.0=h26f9b46_0
  - pandoc=3.8=ha770c72_0
  - pango=1.56.4=hadf4263_0
  - pcre2=10.45=hc749103_0
  - pip=25.2=pyh8b19718_0
  - pixman=0.46.4=h54a6638_1
  - pthread-stubs=0.4=hb9d3cd8_1002
  - python=3.10.18=hd6af730_0_cpython
  - python-dateutil=2.9.0.post0=pyhe01879c_2
  - python-tzdata=2025.2=pyhd8ed1ab_0
  - python_abi=3.10=8_cp310
  - pytz=2025.2=pyhd8ed1ab_0
  - pyyaml=6.0.2=py310h89163eb_2
  - r-abind=1.4_8=r44hc72bb7e_1
  - r-askpass=1.2.1=r44h2b5f3a1_0
  - r-assertthat=0.2.1=r44hc72bb7e_6
  - r-backports=1.5.0=r44h54b55ab_2
  - r-base=4.4.3=h85845a0_2
  - r-base64enc=0.1_3=r44h54b55ab_1008
  - r-bh=1.87.0_1=r44hc72bb7e_1
  - r-bit=4.6.0=r44h54b55ab_1
  - r-bit64=4.6.0_1=r44h54b55ab_1
  - r-bitops=1.0_9=r44h54b55ab_1
  - r-blob=1.2.4=r44hc72bb7e_3
  - r-boot=1.3_32=r44hc72bb7e_1
  - r-brew=1.0_10=r44hc72bb7e_2
  - r-brio=1.1.5=r44h54b55ab_2
  - r-broom=1.0.10=r44hc72bb7e_0
  - r-bslib=0.9.0=r44hc72bb7e_1
  - r-cachem=1.1.0=r44h54b55ab_2
  - r-callr=3.7.6=r44hc72bb7e_2
  - r-car=3.1_3=r44hc72bb7e_1
  - r-cardata=3.0_5=r44hc72bb7e_4
  - r-caret=6.0_94=r44h54b55ab_3
  - r-cellranger=1.1.0=r44hc72bb7e_1008
  - r-circlize=0.4.16=r44hc72bb7e_2
  - r-class=7.3_23=r44h54b55ab_1
  - r-cli=3.6.5=r44h3697838_1
  - r-clipr=0.8.0=r44hc72bb7e_4
  - r-clock=0.7.3=r44h3697838_1
  - r-clue=0.3_66=r44h54b55ab_1
  - r-cluster=2.1.8.1=r44heaba542_1
  - r-codetools=0.2_20=r44hc72bb7e_2
  - r-colorspace=2.1_1=r44h54b55ab_1
  - r-commonmark=2.0.0=r44h54b55ab_1
  - r-conflicted=1.2.0=r44h785f33e_3
  - r-conquer=1.3.3=r44h3704496_5
  - r-corrplot=0.95=r44hc72bb7e_1
  - r-cowplot=1.2.0=r44hc72bb7e_2
  - r-cpp11=0.5.2=r44h785f33e_2
  - r-crayon=1.5.3=r44hc72bb7e_2
  - r-credentials=2.0.3=r44hc72bb7e_0
  - r-crosstalk=1.2.2=r44hc72bb7e_1
  - r-curl=7.0.0=r44h10955f1_1
  - r-data.table=1.17.8=r44h1c8cec4_1
  - r-dbi=1.2.3=r44hc72bb7e_2
  - r-dbplyr=2.5.1=r44hc72bb7e_1
  - r-deriv=4.2.0=r44hc72bb7e_1
  - r-desc=1.4.3=r44hc72bb7e_2
  - r-devtools=2.4.5=r44hc72bb7e_3
  - r-diagram=1.6.5=r44ha770c72_4
  - r-diffobj=0.3.6=r44h54b55ab_1
  - r-digest=0.6.37=r44h3697838_1
  - r-doby=4.7.0=r44hc72bb7e_1
  - r-doparallel=1.0.17=r44hc72bb7e_4
  - r-downlit=0.4.4=r44hc72bb7e_2
  - r-dplyr=1.1.4=r44h3697838_2
  - r-dtplyr=1.3.2=r44hc72bb7e_1
  - r-dunn.test=1.3.6=r44hc72bb7e_2
  - r-e1071=1.7_16=r44h3697838_1
  - r-ellipsis=0.3.2=r44h54b55ab_4
  - r-evaluate=1.0.5=r44hc72bb7e_1
  - r-fansi=1.0.6=r44h54b55ab_2
  - r-farver=2.1.2=r44h3697838_2
  - r-fastmap=1.2.0=r44h3697838_2
  - r-flexparamcurve=1.5_7=r44hc72bb7e_1
  - r-fontawesome=0.5.3=r44hc72bb7e_1
  - r-forcats=1.0.1=r44hc72bb7e_0
  - r-foreach=1.5.2=r44hc72bb7e_4
  - r-formatr=1.14=r44hc72bb7e_3
  - r-formula=1.2_5=r44hc72bb7e_3
  - r-fs=1.6.6=r44h3697838_1
  - r-fsa=0.10.0=r44hc72bb7e_1
  - r-futile.logger=1.4.3=r44hc72bb7e_1007
  - r-futile.options=1.0.1=r44hc72bb7e_1006
  - r-future=1.67.0=r44h785f33e_1
  - r-future.apply=1.20.0=r44hc72bb7e_1
  - r-gargle=1.6.0=r44h785f33e_1
  - r-gbrd=0.4.12=r44hc72bb7e_2
  - r-generics=0.1.4=r44hc72bb7e_1
  - r-gert=2.1.5=r44h5e22a44_0
  - r-getoptlong=1.0.5=r44hc72bb7e_4
  - r-ggplot2=4.0.0=r44h785f33e_0
  - r-ggpubr=0.6.2=r44hc72bb7e_0
  - r-ggrepel=0.9.6=r44h3697838_2
  - r-ggsci=4.0.0=r44hc72bb7e_0
  - r-ggsignif=0.6.4=r44hc72bb7e_3
  - r-gh=1.5.0=r44hc72bb7e_0
  - r-gitcreds=0.1.2=r44hc72bb7e_4
  - r-globaloptions=0.1.2=r44ha770c72_4
  - r-globals=0.18.0=r44hc72bb7e_1
  - r-glue=1.8.0=r44h54b55ab_1
  - r-googledrive=2.1.2=r44hc72bb7e_1
  - r-googlesheets4=1.1.2=r44h785f33e_1
  - r-gower=1.0.1=r44h54b55ab_3
  - r-gridextra=2.3=r44hc72bb7e_1007
  - r-gtable=0.3.6=r44hc72bb7e_1
  - r-hardhat=1.4.2=r44hc72bb7e_1
  - r-haven=2.5.5=r44h6d565e7_1
  - r-hexbin=1.28.5=r44heaba542_1
  - r-highr=0.11=r44hc72bb7e_2
  - r-hms=1.1.3=r44hc72bb7e_3
  - r-htmltools=0.5.8.1=r44h3697838_2
  - r-htmlwidgets=1.6.4=r44h785f33e_4
  - r-httpuv=1.6.16=r44h6d565e7_1
  - r-httr=1.4.7=r44hc72bb7e_1
  - r-httr2=1.2.1=r44hc72bb7e_0
  - r-ids=1.0.1=r44hc72bb7e_5
  - r-ini=0.3.1=r44hc72bb7e_1007
  - r-ipred=0.9_15=r44h54b55ab_2
  - r-isoband=0.2.7=r44h3697838_4
  - r-iterators=1.0.14=r44hc72bb7e_4
  - r-jquerylib=0.1.4=r44hc72bb7e_4
  - r-jsonlite=2.0.0=r44h54b55ab_1
  - r-kernsmooth=2.23_26=r44ha0a88a1_1
  - r-knitr=1.50=r44hc72bb7e_1
  - r-labeling=0.4.3=r44hc72bb7e_2
  - r-lambda.r=1.2.4=r44hc72bb7e_5
  - r-later=1.4.4=r44h3697838_1
  - r-lattice=0.22_7=r44h54b55ab_1
  - r-lava=1.8.1=r44hc72bb7e_1
  - r-lazyeval=0.2.2=r44h54b55ab_6
  - r-lifecycle=1.0.4=r44hc72bb7e_2
  - r-listenv=0.9.1=r44hc72bb7e_2
  - r-lme4=1.1_37=r44h3697838_2
  - r-lmtest=0.9_40=r44heaba542_4
  - r-lubridate=1.9.4=r44h54b55ab_1
  - r-magrittr=2.0.4=r44h54b55ab_0
  - r-mass=7.3_65=r44h54b55ab_0
  - r-matrix=1.7_4=r44h0e4624f_1
  - r-matrixmodels=0.5_4=r44hc72bb7e_1
  - r-matrixstats=1.5.0=r44h54b55ab_1
  - r-memoise=2.0.1=r44hc72bb7e_4
  - r-mgcv=1.9_3=r44h0e4624f_1
  - r-microbenchmark=1.5.0=r44h54b55ab_1
  - r-mime=0.13=r44h54b55ab_1
  - r-miniui=0.1.2=r44hc72bb7e_1
  - r-minqa=1.2.8=r44ha36cffa_2
  - r-modelmetrics=1.2.2.2=r44h3697838_5
  - r-modelr=0.1.11=r44hc72bb7e_3
  - r-munsell=0.5.1=r44hc72bb7e_2
  - r-nlme=3.1_168=r44heaba542_1
  - r-nloptr=2.2.1=r44h8ae9fae_1
  - r-nnet=7.3_20=r44h54b55ab_1
  - r-nortest=1.0_4=r44hc72bb7e_1007
  - r-numderiv=2016.8_1.1=r44hc72bb7e_7
  - r-openssl=2.3.3=r44he8289e2_0
  - r-parallelly=1.45.1=r44h54b55ab_1
  - r-pbkrtest=0.5.5=r44hc72bb7e_1
  - r-pheatmap=1.0.13=r44hc72bb7e_1
  - r-pillar=1.11.0=r44hc72bb7e_1
  - r-pkgbuild=1.4.8=r44hc72bb7e_1
  - r-pkgconfig=2.0.3=r44hc72bb7e_5
  - r-pkgdown=2.1.3=r44hc72bb7e_0
  - r-pkgload=1.4.0=r44hc72bb7e_1
  - r-plotly=4.11.0=r44hc72bb7e_1
  - r-plotrix=3.8_4=r44hc72bb7e_2
  - r-plyr=1.8.9=r44h3697838_3
  - r-png=0.1_8=r44h6b2d295_3
  - r-polynom=1.4_1=r44hc72bb7e_4
  - r-praise=1.0.0=r44hc72bb7e_1009
  - r-prettyunits=1.2.0=r44hc72bb7e_2
  - r-proc=1.19.0.1=r44h3697838_1
  - r-processx=3.8.6=r44h54b55ab_1
  - r-prodlim=2025.04.28=r44h3697838_1
  - r-profvis=0.4.0=r44h54b55ab_1
  - r-progress=1.2.3=r44hc72bb7e_2
  - r-progressr=0.17.0=r44hc72bb7e_0
  - r-promises=1.3.3=r44h3697838_1
  - r-proxy=0.4_27=r44h54b55ab_4
  - r-ps=1.9.1=r44h54b55ab_1
  - r-purrr=1.1.0=r44h54b55ab_1
  - r-quantreg=6.1=r44h11cdb10_1
  - r-r6=2.6.1=r44hc72bb7e_1
  - r-ragg=1.5.0=r44h9f1dc4d_1
  - r-rappdirs=0.3.3=r44h54b55ab_4
  - r-rbibutils=2.3=r44h54b55ab_1
  - r-rcmdcheck=1.4.0=r44h785f33e_3
  - r-rcolorbrewer=1.1_3=r44h785f33e_4
  - r-rcpp=1.1.0=r44h3697838_1
  - r-rcpparmadillo=15.0.2_2=r44h3704496_0
  - r-rcppeigen=0.3.4.0.2=r44h3704496_1
  - r-rcurl=1.98_1.17=r44hb79926e_1
  - r-rdpack=2.6.4=r44hc72bb7e_1
  - r-readr=2.1.5=r44h3697838_2
  - r-readxl=1.4.5=r44h10e25cc_1
  - r-recipes=1.3.1=r44hc72bb7e_1
  - r-reformulas=0.4.1=r44hc72bb7e_1
  - r-rematch=2.0.0=r44hc72bb7e_2
  - r-rematch2=2.1.2=r44hc72bb7e_5
  - r-remotes=2.5.0=r44hc72bb7e_2
  - r-reprex=2.1.1=r44hc72bb7e_2
  - r-reshape2=1.4.4=r44h3697838_6
  - r-restfulr=0.0.16=r44h5ef9028_0
  - r-rjson=0.2.23=r44h3697838_1
  - r-rlang=1.1.6=r44h3697838_1
  - r-rmarkdown=2.29=r44hc72bb7e_1
  - r-roxygen2=7.3.3=r44h3697838_1
  - r-rpart=4.1.24=r44h54b55ab_1
  - r-rprojroot=2.1.1=r44hc72bb7e_1
  - r-rstatix=0.7.3=r44hc72bb7e_0
  - r-rstudioapi=0.17.1=r44hc72bb7e_1
  - r-rversions=2.1.2=r44hc72bb7e_3
  - r-rvest=1.0.5=r44hc72bb7e_1
  - r-s7=0.2.0=r44h54b55ab_1
  - r-sass=0.4.10=r44h3697838_1
  - r-scales=1.4.0=r44hc72bb7e_1
  - r-selectr=0.4_2=r44hc72bb7e_5
  - r-sessioninfo=1.2.3=r44hc72bb7e_1
  - r-shape=1.4.6.1=r44ha770c72_2
  - r-shiny=1.11.1=r44h785f33e_1
  - r-snow=0.4_4=r44hc72bb7e_4
  - r-sourcetools=0.1.7_1=r44h3697838_3
  - r-sparsem=1.84_2=r44heaba542_1
  - r-sparsevctrs=0.3.4=r44h54b55ab_1
  - r-squarem=2021.1=r44hc72bb7e_4
  - r-stringi=1.8.7=r44h2dae267_1
  - r-stringr=1.5.2=r44h785f33e_1
  - r-survival=3.8_3=r44h54b55ab_1
  - r-sys=3.4.3=r44h54b55ab_1
  - r-systemfonts=1.2.3=r44h74f4acd_1
  - r-testthat=3.2.3=r44h3697838_2
  - r-textshaping=1.0.3=r44h74f4acd_1
  - r-tibble=3.3.0=r44h54b55ab_1
  - r-tidyr=1.3.1=r44h3697838_2
  - r-tidyselect=1.2.1=r44hc72bb7e_2
  - r-tidyverse=2.0.0=r44h785f33e_3
  - r-timechange=0.3.0=r44h3697838_2
  - r-timedate=4051.111=r44hc72bb7e_0
  - r-tinytex=0.57=r44hc72bb7e_1
  - r-tzdb=0.5.0=r44h3697838_2
  - r-urlchecker=1.0.1=r44hc72bb7e_3
  - r-usethis=3.2.1=r44hc72bb7e_0
  - r-utf8=1.2.6=r44h54b55ab_1
  - r-uuid=1.2_1=r44h54b55ab_1
  - r-vctrs=0.6.5=r44h3697838_2
  - r-viridislite=0.4.2=r44hc72bb7e_3
  - r-vroom=1.6.6=r44h3697838_0
  - r-waldo=0.6.2=r44hc72bb7e_1
  - r-whisker=0.4.1=r44hc72bb7e_3
  - r-withr=3.0.2=r44hc72bb7e_1
  - r-xfun=0.53=r44h3697838_1
  - r-xml=3.99_0.17=r44h7c9d5c0_3
  - r-xml2=1.4.0=r44hc6fd541_1
  - r-xopen=1.0.1=r44hc72bb7e_2
  - r-xtable=1.8_4=r44hc72bb7e_7
  - r-yaml=2.3.10=r44h54b55ab_1
  - r-zip=2.3.3=r44h54b55ab_1
  - r-zoo=1.8_14=r44h54b55ab_1
  - readline=8.2=h8c095d6_2
  - samtools=1.22.1=h96c455f_0
  - sed=4.9=h6688a6e_0
  - setuptools=80.9.0=pyhff2d567_0
  - six=1.17.0=pyhe01879c_1
  - sysroot_linux-64=2.28=h4ee821c_8
  - tk=8.6.13=noxft_hd72426e_102
  - tktable=2.10=h8d826fa_7
  - toml=0.10.2=pyhd8ed1ab_1
  - tomlkit=0.13.3=pyha770c72_0
  - tzdata=2025b=h78e105d_0
  - wheel=0.45.1=pyhd8ed1ab_1
  - xmltodict=1.0.1=pyhcf101f3_0
  - xorg-libice=1.1.2=hb9d3cd8_0
  - xorg-libsm=1.2.6=he73a12e_0
  - xorg-libx11=1.8.12=h4f16b4b_0
  - xorg-libxau=1.0.12=hb9d3cd8_0
  - xorg-libxdmcp=1.1.5=hb9d3cd8_0
  - xorg-libxext=1.3.6=hb9d3cd8_0
  - xorg-libxrender=0.9.12=hb9d3cd8_0
  - xorg-libxt=1.3.1=hb9d3cd8_0
  - yaml=0.2.5=h280c20c_3
  - yq=3.4.3=pyhe01879c_2
  - zstd=1.5.7=hb8e6e7a_2
  - pip:
      - comut==0.0.3
      - contourpy==1.3.2
      - cycler==0.12.1
      - fonttools==4.59.2
      - kiwisolver==1.4.9
      - matplotlib==3.10.6
      - oncodriveclust==1.0.0
      - packaging==25.0
      - palettable==3.3.3
      - pandas==2.3.2
      - patsy==1.0.1
      - pillow==11.3.0
      - pyparsing==3.2.4
      - pysam==0.23.3
      - scipy==1.15.3
      - seaborn==0.13.2
      - statsmodels==0.14.5
      - tabulate==0.9.0
      - termcolor==3.1.0
      - tqdm==4.67.1
      - vcfpy==0.13.8
prefix: /home/cpastor/miniforge3/envs/impact_vuscan
